# -*- coding: utf-8 -*-
"""image_classification_with_mobilenet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PdfvX5S9eH7HzQr0jaUX-00gWZKS3YA
"""

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input, decode_predictions
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

# Load MobileNetV2 model pre-trained on ImageNet
model = MobileNetV2(weights="imagenet")

# Load and preprocess the image
img_path = "/content/drive/MyDrive/Colab Notebooks/pics/sammy.jpg"
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

img

x.shape

# Make prediction
preds = model.predict(x)
decoded = decode_predictions(preds, top=3)[0]

# Print top 3 predictions
print("Top 3 Predictions:")
for i, (imagenetID, label, prob) in enumerate(decoded):
    print(f"{i+1}. {label}: {prob*100:.2f}%")

# Plot image and predictions
plt.imshow(img)
plt.title("Predicted: " + decoded[0][1])
plt.axis('off')
plt.show()

