# -*- coding: utf-8 -*-
"""yolov8_detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QPovB_-Giq7KtVjvx-XyNY3KgMjnIa5q
"""

# install ultralytics
!pip install ultralytics

from ultralytics import YOLO
import cv2

# Load YOLOv8 model (Nano version for speed)
model = YOLO("yolov8n.pt")

# Load an image
image_path = "/content/drive/MyDrive/Colab Notebooks/pics/sammy.jpg"
image = cv2.imread(image_path)

from google.colab.patches import cv2_imshow
cv2_imshow(image)

# Run inference
results = model(image)

# Plot results
annotated_frame = results[0].plot()

# Display image
cv2_imshow(annotated_frame)

