# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8qmHS_cpEn9TvFZq1mhWPoT0wA7qNrU
"""

# Install dependencies
!pip install streamlit==1.34.0
!pip install SpeechRecognition==3.10.0
!pip install pydub
!apt-get install ffmpeg -y  # Required for audio conversion (e.g. MP3 to WAV)

# Import necessary libraries
import os
import tempfile
import speech_recognition as sr
from pydub import AudioSegment
from IPython.display import Audio

# Upload audio file
from google.colab import files
uploaded = files.upload()

# Convert to WAV format if necessary
uploaded_filename = list(uploaded.keys())[0]
if uploaded_filename.endswith('.mp3'):
    audio = AudioSegment.from_mp3(uploaded_filename)
    wav_filename = uploaded_filename.replace('.mp3', '.wav')
    audio.export(wav_filename, format='wav')
elif uploaded_filename.endswith('.wav'):
    wav_filename = uploaded_filename
else:
    raise ValueError("Unsupported file format. Upload .mp3 or .wav")

# Transcribe audio
recognizer = sr.Recognizer()
with sr.AudioFile(wav_filename) as source:
    audio_data = recognizer.record(source)

print("🎧 Transcribing your audio...")
try:
    text = recognizer.recognize_google(audio_data)
    print("\n✅ Transcription:")
    print(text)
except sr.UnknownValueError:
    print("❌ Could not understand the audio.")
except sr.RequestError:
    print("❌ Google API request failed.")

# Optional: Play audio in notebook
Audio(wav_filename)

