# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRY9dkYe72BCT-86-PQ15gx_jmT-Ggow
"""

!pip install streamlit spacy
!python -m spacy download en_core_web_sm

import streamlit
import spacy
from spacy import displacy

# load spacy model
nlp = spacy.load("en_core_web_sm")

# app title
streamlit.title("NLP Visualizer with spaCy + Streamlit")
streamlit.markdown("Type or paste any text below and see token analysis, POS tags, and Named Entities!")

# text input
text_input = streamlit.text_area("Enter your text here:", "Apple is looking at buying a U.K. startup for $1 billion.")

if streamlit.button("Analyze"):
    doc = nlp(text_input)

    streamlit.subheader("🧾 Tokens and POS Tags")
    for token in doc:
        streamlit.write(f"{token.text} — {token.pos_} ({spacy.explain(token.pos_)})")

    streamlit.subheader("🏷 Named Entities")
    if doc.ents:
        for ent in doc.ents:
            streamlit.markdown(f"- **{ent.text}** → {ent.label_} ({spacy.explain(ent.label_)})")
    else:
        streamlit.write("No named entities found.")

    streamlit.subheader("🖼 Visualize Entities")
    html = displacy.render(doc, style="ent", jupyter=False)
    streamlit.components.v1.html(html, scrolling=True)

